<?php
require_once __DIR__ . '/functions.php';
$pdo=db();$id=(int)($_GET['id']??0);
$stmt=$pdo->prepare("SELECT p.*,c.title category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.id=? AND p.status='active' LIMIT 1");$stmt->execute([$id]);$p=$stmt->fetch();
if(!$p){http_response_code(404);exit('Product not found');}
$pd=product_price_data($p);
$reviewsStmt=$pdo->prepare("SELECT r.*,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? ORDER BY r.created_at DESC");$reviewsStmt->execute([$id]);$reviews=$reviewsStmt->fetchAll();
$rating=$reviews?round(array_sum(array_column($reviews,'rating'))/count($reviews),1):0;
$relatedStmt=$pdo->prepare("SELECT p.*,c.title category FROM products p JOIN categories c ON c.id=p.category_id WHERE p.category_id=? AND p.id<>? AND p.status='active' ORDER BY p.created_at DESC LIMIT 4");$relatedStmt->execute([$p['category_id'],$id]);$related=$relatedStmt->fetchAll();
$title=$p['name'];include __DIR__.'/partials/header.php';
?>
<section class="page"><div class="container">
  <div class="breadcrumbs"><a href="<?=BASE_URL?>/products.php">Shop</a><span>›</span><a href="<?=BASE_URL?>/products.php?category=<?=$p['category_id']?>"><?=e($p['category'])?></a><span>›</span><b><?=e($p['name'])?></b></div>
  <div class="product-detail-pro">
    <div class="detail-gallery"><div class="detail-image-wrap"><?php if($pd['discount']):?><span class="discount-badge detail-discount">-<?=$pd['discount']?>% OFF</span><?php endif;?><img class="detail-img" src="<?=product_image($p['image'])?>" alt="<?=e($p['name'])?>"></div></div>
    <div class="detail-pro-content"><span class="badge"><?=e($p['category'])?></span><h1><?=e($p['name'])?></h1><div class="rating-line"><span class="stars"><?=str_repeat('★',(int)round($rating))?><?=str_repeat('☆',5-(int)round($rating))?></span><span><?=number_format($rating,1)?> · <?=count($reviews)?> reviews</span></div>
      <div class="detail-price"><strong><?=money($p['price'])?></strong><?php if($pd['discount']):?><del><?=money($pd['compare_price'])?></del><span><?=$pd['discount']?>% OFF</span><?php endif;?></div>
      <?php if($pd['discount']):?><div class="deal-box"><b>Special offer</b><span>You save <?=money($pd['compare_price']-$pd['price'])?> on this product.</span></div><?php endif;?>
      <div class="detail-stock"><span class="stock-dot"></span><?=((int)$p['stock']>0?'In stock':'Out of stock')?> <span>•</span> <?=((int)$p['stock']>0?(int)$p['stock'].' units available':'Currently unavailable')?></div>
      <p class="detail-description"><?=nl2br(e($p['content']))?></p>
      <div class="feature-strip"><div><b>✓</b><span>Authentic product</span></div><div><b>✓</b><span>Home delivery</span></div><div><b>✓</b><span>Secure checkout</span></div></div>
      <?php if((int)$p['stock']>0):?><form method="post" action="<?=BASE_URL?>/cart.php" class="buy-box"><?=csrf_field()?><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?=$id?>"><label>Quantity<input name="quantity" type="number" min="1" max="<?=$p['stock']?>" value="1"></label><button class="btn btn-primary">Add to Cart</button></form><form method="post" action="<?=BASE_URL?>/cart.php" class="buy-now-inline"><?=csrf_field()?><input type="hidden" name="action" value="buy_now"><input type="hidden" name="product_id" value="<?=$id?>"><input type="hidden" name="quantity" value="1"><button class="btn btn-dark">Buy Now</button></form><?php else:?><div class="notice">This product is currently out of stock.</div><?php endif;?>
    </div>
  </div>
  <div class="detail-lower"><section class="panel"><div class="section-head"><div><span class="eyebrow">PRODUCT INFORMATION</span><h2>Details</h2></div></div><div class="spec-grid"><div><span>Category</span><b><?=e($p['category'])?></b></div><div><span>Delivery</span><b><?=e($p['delivery_kind'])?></b></div><div><span>Availability</span><b><?=((int)$p['stock']>0?'In stock':'Out of stock')?></b></div><div><span>Product ID</span><b>#<?=e($p['id'])?></b></div></div><div class="long-description"><?=nl2br(e($p['content']))?></div></section>
    <section class="panel"><div class="section-head"><div><span class="eyebrow">CUSTOMER FEEDBACK</span><h2>Reviews</h2></div><span class="muted"><?=count($reviews)?> review(s)</span></div><?php if(is_logged_in() && user()['role']==='buyer'):?><form method="post" action="<?=BASE_URL?>/review.php" class="form-grid"><input type="hidden" name="product_id" value="<?=$id?>"><?=csrf_field()?><div class="field"><label>Rating</label><select name="rating"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></div><div class="field full"><label>Your review</label><textarea name="comment" rows="3" required></textarea></div><button class="btn btn-primary">Submit Review</button></form><hr><?php endif;?><?php foreach($reviews as $r):?><div class="review-row"><div><b><?=e($r['name'])?></b><span class="stars"><?=str_repeat('★',(int)$r['rating'])?></span></div><p><?=e($r['comment'])?></p><small><?=e($r['created_at'])?></small></div><?php endforeach;?><?php if(!$reviews):?><p class="muted">No reviews yet. Be the first to review this product.</p><?php endif;?></section>
  </div>
  <?php if($related):?><section class="section related-section"><div class="section-head"><div><span class="eyebrow">YOU MAY ALSO LIKE</span><h2>More from <?=e($p['category'])?></h2></div></div><div class="grid"><?php foreach($related as $r):$rd=product_price_data($r);?><article class="card product-card"><a class="product-media" href="product.php?id=<?=$r['id']?>"><?php if($rd['discount']):?><span class="discount-badge">-<?=$rd['discount']?>%</span><?php endif;?><img class="product-img" src="<?=product_image($r['image'])?>"></a><div class="card-body"><span class="badge"><?=e($r['category'])?></span><h3><?=e($r['name'])?></h3><div class="price-row"><strong class="price"><?=money($r['price'])?></strong><?php if($rd['discount']):?><del><?=money($rd['compare_price'])?></del><?php endif;?></div></div></article><?php endforeach;?></div></section><?php endif;?>
</div></section>
<?php include __DIR__.'/partials/footer.php'; ?>
